version: '3.8'

services:
  app:
    container_name: jira-app
    image: jira-app
    depends_on:
      - db
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
  db:
    container_name: db
    image: postgres:latest
    restart: always
    #    user: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
